version: 1
disable_existing_loggers: False

formatters:
  default:
    "()": "uvicorn.logging.DefaultFormatter"
    fmt: "%(levelprefix)s %(message)s"
    use_colors: True
  access:
    "()": "uvicorn.logging.AccessFormatter"
    fmt: '%(levelprefix)s %(client_addr)s - "%(request_line)s" %(status_code)s'
    use_colors: True

handlers:
  default:
    formatter: default
    class: logging.StreamHandler
    stream: ext://sys.stderr
  access:
    formatter: access
    class: logging.StreamHandler
    stream: ext://sys.stdout

loggers:
  uvicorn:
    handlers: [default]
    level: INFO
    propagate: no
  uvicorn.error:
    level: INFO
  uvicorn.access:
    handlers: [access]
    level: INFO
    propagate: no
  watchfiles:
    handlers: [default]
    level: WARNING
